theme: jekyll-theme-minimal
name: Titouan Vayer
markdown: kramdown
title: Degemer mat !
author_email: titouan.vayer@irisa.fr
description: Optimal Transport. Structured Data. 
avatar: https://avatars0.githubusercontent.com/u/17176077?s=400&u=c316b069b096c32d121c17af4391167ea900d924&v=4
