theme: jekyll-theme-minimal
name: Titouan Vayer
markdown: kramdown
title: Degemer mat !
author_email: titouan.vayer@irisa.fr
description: Optimal Transport. Structured Data. 
avatar: "tvayer.github.io/materials/me.png"
